name: TopMineLeaderboard
api: [4.0.0]
version: 1.0.0
author: reyyoga & AlvinHere
main: reyyoga\Main

commands:
 settopmine:
     description: set leaderboard location
permissions:
  settopmine.lb:
    description: topmineleaderboard permission!
    default: op
